### ISSUE TITLE
UnboundLocalError: local variable 'available_ports' referenced before assignment

### ISSUE THREAD

**Issue by farvardin** [zuggamasta/midiTracker#43]
hello, 
i'm using Python 3.10.12 on linux (mint 21.3)  and I've setup the venv environement according to the manual there https://github.com/zuggamasta/midiTracker/wiki/01-Installing-midiTracker-(Beginner-Friendly)

after starting miditracker with ``python3 midiTracker.py``, I saw the logo moving to the left, and then it crashed saying:

```
Traceback (most recent call last):
  File "/temp/github/music/midiTracker/midiTracker.py", line 994, in <module>
    wrapper(main)
  File "/usr/lib/python3.10/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/temp/github/music/midiTracker/midiTracker.py", line 981, in main
    if not current_screen == 4: draw_info(info_win,available_ports[MIDI_PORT])        
UnboundLocalError: local variable 'available_ports' referenced before assignment
```

**Comment by zuggamasta** [comment]
This is due to some issue in one of the modules I use. You did everything right, but for now version **3.9.xx** is required. Im sorry for that inconvenience. I'll hopefully be able to fix this in the next weeks. 

I was struggling with that exact same error for weeks.

**Comment by estufilla** [comment]
Happens the same to me on 3.9.10. Weird.

`(midiTracker) estufa@uConsole:~/gits/midiTracker $ python3 midiTracker.py 
             Traceback (most recent call last):
             File "/home/estufa/gits/midiTracker/midiTracker.py", line 994, in <module>
    wrapper(main)
            File "/home/estufa/.pyenv/versions/3.9.10/lib/python3.9/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
           File "/home/estufa/gits/midiTracker/midiTracker.py", line 981, in main
    if not current_screen == 4: draw_info(info_win,available_ports[MIDI_PORT])
           UnboundLocalError: local variable 'available_ports' referenced before assignment
(midiTracker) estufa@uConsole:~/gits/midiTracker $ python3 -V
           Python 3.9.10
`

**Comment by zuggamasta** [comment]
Oh gosh. Sorry that you both had to encounter that issue.

Thank you for trying out 3.9.10 and reporting. I'll let you know as soon as I figure out more.

**Comment by estufilla** [comment]
Hey, thanks to you for making this and sharing it for everyone, no need to say sorry !Sorry I cannot
be more helpful, but I'll tell if find anything.

**Comment by estufilla** [comment]
Hey! 

Hi Zugga and farva, sorry for the double post, but I was on the move on the other one so I couldn't explain myself properly.

I didn't give a lot of info on my system, which shouldn't matter with python as I understand (sorry, I saw my first terminal like 2 months ago, I'm trying hard haha). It's an uConsole with CM4 module (RPi4 basically), running Debian. I already had previously Python 3.11 installed, and used pyenv to get 3.9.10 (as I saw somewhere was the version you used). It didn't work so I downloaded the 3.9 source and compiled with the proper libs. Didn't work either. I have Manjaro in my PC with 3.11 from beforehand, and happened the same.

As I can simply swap microSD and get another system, I'll install arch from scratch and get Python 3.9.10 clean, and try again to see what happens.



I'll report back!

**Comment by estufilla** [comment]
I tried in 4 different machines. The uConsole, my main PC, my father's PC, and basically 1 Debian chroot and 1 Arch chroot on my Android device. Nothing worked, all 3.9.10, same error.

I did manage to get something different in my main machine. Still, 3.9.10, no idea what I've done here.

```
   ~/gits/midiTracker    main ?2  python3 midiTracker.py                                                                                                                                                      1 ✘  tracker 3.9.10  
Traceback (most recent call last):
  File "/home/estufa/gits/midiTracker/midiTracker.py", line 994, in <module>
    wrapper(main)
  File "/home/estufa/.pyenv/versions/3.9.10/lib/python3.9/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/home/estufa/gits/midiTracker/midiTracker.py", line 988, in main
    play_song(0)
  File "/home/estufa/gits/midiTracker/midiTracker.py", line 534, in play_song
    play_notes(current_notes_buffer,current_modifier_buffer,current_cc_buffer)
  File "/home/estufa/gits/midiTracker/midiTracker.py", line 610, in play_notes
    outport.send(Message('note_on', channel=channel, note=notes[channel], velocity=120))
AttributeError: 'NoneType' object has no attribute 'send'
```


Note: git status changed as I added a pyenv version on folder.

EDIT: How can I format this properly? So noob sorry! It literally hurts to try and read lmao.
EDIT2: Sorry won't edit anymore, don't want to be giving false alarms here (idk if it gives notifs). If anyone can point me to the right direction... I can start it, but can't tell to stop it XD
EDIT3: Yep, sorry, got it. Nothing to se here. :)

**Comment by zuggamasta** [comment]
Thank you again for trying this out. I have a bad feeling there might be a step missing in my manual. I now have the time to do new first time installs myself. I'll let you know how it goes.

**Comment by estufilla** [comment]
Hey!

Seriously, again thanks to you for taking your time to make it and maintain
it!

I'll keep trying myself. I was thinking before, I always pulled the git but
didn't try to use any release. I'll try that after.

**Comment by zuggamasta** [comment]
No need to try the releases. Cloning the git is a good way to stay on track. I figured something out: You'll need to create a new venv for that, writing very verbose to make myself aware of any issues, too:

0. `git clone https://github.com/zuggamasta/midiTracker.git`
1. `cd midiTracker/`
2. `python3 -m venv venv/` <-- or use your python3.10 
3. `source venv/bin/activate` 
4. `python -V` --> verifying that we're in the venv and using the correct version Python 3.10.13 in my case
5. `python -m pip install mido`
6. `python -m pip install python-rtmidi`
7. `python midiTracker.py`

Somehow my first setups all involved both versions of rtmidi, but I ran like this and I got the exact error message as soon as I also installed the "rtmidi" package as noted in my install notes. I now removed that step from the notes.

I hope this gets you started!

**Comment by estufilla** [comment]
![2024-05-02-14-13-49-776](https://github.com/zuggamasta/midiTracker/assets/124872620/fc01615d-fbdd-4517-a868-4c2bcbeeec3c)

You're a beast. Now to try and figure out how to resize this xD

**Comment by zuggamasta** [comment]
If it's behaving like a regular raspberryPi, quoting my own [forum post](https://www.modwiggler.com/forum/viewtopic.php?t=257717) :

> Go in and use one of the shipped fonts. After selecting one you will get to select the size from a list of options. These sizes will vary from font to font. It might be possible to load custom fonts, but I yet have to find one that is a suitable bitmap font. [https://www.raspberrypi-spy.co.uk/2014/ ... font-size/](https://www.raspberrypi-spy.co.uk/2014/04/how-to-change-the-command-line-font-size/)


Closing this ticket for now. Feel free to open a new one any time.
